// Sentence Builder bank. tag = grammar point shown as a label.
// Sentences must have exactly one natural word order (no swappable clauses).
window.BUILD_SENTENCES = [
  { tag: "Present Simple", s: "She works in a hospital" },
  { tag: "Present Simple", s: "The train leaves at seven" },
  { tag: "Present Simple", s: "He rarely eats meat" },
  { tag: "Present Simple", s: "Water boils at one hundred degrees" },
  { tag: "Present Continuous", s: "They are building a new bridge" },
  { tag: "Present Continuous", s: "I am looking for my keys" },
  { tag: "Present Continuous", s: "She is working from home today" },
  { tag: "Present Continuous", s: "Prices are rising quickly" },
  { tag: "Past Simple", s: "We moved to Berlin in 2019" },
  { tag: "Past Simple", s: "The meeting ended an hour ago" },
  { tag: "Past Simple", s: "She studied law at university" },
  { tag: "Past Simple", s: "I lost my phone yesterday" },
  { tag: "Past Continuous", s: "I was cooking when you called" },
  { tag: "Past Continuous", s: "They were living abroad at the time" },
  { tag: "Past Continuous", s: "It was raining all morning" },
  { tag: "Present Perfect", s: "I have never been to Japan" },
  { tag: "Present Perfect", s: "She has just finished the report" },
  { tag: "Present Perfect", s: "We have known each other for years" },
  { tag: "Present Perfect", s: "He has already left" },
  { tag: "Future", s: "I will call you tomorrow" },
  { tag: "Future", s: "We are going to miss the train" },
  { tag: "Future", s: "The shop will close at nine" },
  { tag: "Future", s: "It is going to rain soon" },
  { tag: "Modals", s: "You should see a doctor" },
  { tag: "Modals", s: "We must leave before noon" },
  { tag: "Modals", s: "She can speak three languages" },
  { tag: "Questions", s: "How long have you lived here" },
  { tag: "Questions", s: "What does this word mean" },
  { tag: "Questions", s: "Where were you last night" },
  { tag: "Gerunds & Infinitives", s: "I enjoy working from home" },
  { tag: "Gerunds & Infinitives", s: "He decided to sell the house" },
  { tag: "Gerunds & Infinitives", s: "She avoided answering the question" },
  { tag: "Passive", s: "The room is cleaned every day" },
  { tag: "Passive", s: "The bridge was built in 1900" },
  { tag: "Passive", s: "My car is being repaired" },
  { tag: "Passive", s: "The results will be announced tomorrow" },
  { tag: "Conditionals", s: "If it rains we will cancel the trip" },
  { tag: "Conditionals", s: "If I were you I would take the job" },
  { tag: "Conditionals", s: "If you heat ice it melts" },
  { tag: "Conditionals", s: "If I had known I would have called you" },
  { tag: "Relative Clauses", s: "The man who called you is my boss" },
  { tag: "Relative Clauses", s: "The book that I ordered arrived today" },
  { tag: "Relative Clauses", s: "She married a man whose family owns a hotel" },
  { tag: "Reported Speech", s: "He said that he was tired" },
  { tag: "Reported Speech", s: "She told me that she would come" },
  { tag: "Reported Speech", s: "They asked where I lived" }
];
