// Grammar exercise bank. Each topic has questions.
// Types: "mc" = multiple choice, "fill" = type the answer (accepts variants).
window.TOPICS = [
  {
    id: "articles",
    title: "Articles",
    blurb: "a / an / the / —",
    questions: [
      { type: "mc", q: "She is ___ honest person.", options: ["a", "an", "the", "—"], answer: "an",
        why: "Use 'an' before a vowel SOUND. 'Honest' starts with a silent h, so the sound is a vowel." },
      { type: "mc", q: "I saw ___ moon clearly last night.", options: ["a", "an", "the", "—"], answer: "the",
        why: "Unique things (the moon, the sun, the sky) take 'the'." },
      { type: "mc", q: "He works as ___ engineer.", options: ["a", "an", "the", "—"], answer: "an",
        why: "Jobs take a/an. 'Engineer' starts with a vowel sound → 'an'." },
      { type: "mc", q: "___ water is essential for life.", options: ["A", "An", "The", "—"], answer: "—",
        why: "Uncountable nouns used in a general sense take no article." },
      { type: "mc", q: "I bought ___ umbrella because it was raining.", options: ["a", "an", "the", "—"], answer: "an",
        why: "'Umbrella' starts with a vowel sound /ʌ/ → 'an'." },
      { type: "mc", q: "She plays ___ piano beautifully.", options: ["a", "an", "the", "—"], answer: "the",
        why: "Musical instruments take 'the': play the piano, the guitar." },
      { type: "mc", q: "We had ___ wonderful time in Italy.", options: ["a", "an", "the", "—"], answer: "a",
        why: "'Wonderful' starts with a consonant sound /w/ → 'a'. Singular countable noun needs an article." },
      { type: "mc", q: "He is ___ tallest boy in the class.", options: ["a", "an", "the", "—"], answer: "the",
        why: "Superlatives (tallest, best, most) take 'the'." },
    ],
  },
  {
    id: "tenses",
    title: "Verb Tenses",
    blurb: "past, present perfect, continuous…",
    questions: [
      { type: "mc", q: "I ___ here since 2019.", options: ["live", "lived", "have lived", "am living"], answer: "have lived",
        why: "'Since' + a point in time → present perfect (action continues to now)." },
      { type: "mc", q: "While I ___ TV, the phone rang.", options: ["watched", "was watching", "watch", "have watched"], answer: "was watching",
        why: "Past continuous for the longer background action interrupted by a short past action." },
      { type: "fill", q: "Type the correct form: 'She ___ (go) to bed when the alarm went off.'", answer: ["was going", "had gone"],
        why: "Past continuous 'was going' (in progress) is most natural here." },
      { type: "mc", q: "By the time we arrived, the film ___.", options: ["started", "has started", "had started", "was starting"], answer: "had started",
        why: "Past perfect for an action completed before another past action." },
      { type: "mc", q: "Water ___ at 100 degrees Celsius.", options: ["boils", "is boiling", "boiled", "has boiled"], answer: "boils",
        why: "Present simple for general facts and truths." },
      { type: "mc", q: "Look! It ___.", options: ["rains", "is raining", "rained", "has rained"], answer: "is raining",
        why: "Present continuous for something happening right now." },
      { type: "fill", q: "Type the correct form: 'I ___ (not / see) him since Monday.'", answer: ["haven't seen", "have not seen"],
        why: "Present perfect with 'since' for an action up to now: have not seen." },
      { type: "mc", q: "They ___ to Spain next summer.", options: ["go", "are going", "went", "have gone"], answer: "are going",
        why: "Present continuous for fixed future plans." },
    ],
  },
  {
    id: "prepositions",
    title: "Prepositions",
    blurb: "in / on / at / by …",
    questions: [
      { type: "mc", q: "The meeting is ___ Monday.", options: ["in", "on", "at", "by"], answer: "on",
        why: "Days and dates take 'on': on Monday, on July 4th." },
      { type: "mc", q: "I'll see you ___ the morning.", options: ["in", "on", "at", "by"], answer: "in",
        why: "Parts of the day take 'in': in the morning/afternoon/evening. But 'at night'." },
      { type: "mc", q: "She arrives ___ 6 o'clock.", options: ["in", "on", "at", "by"], answer: "at",
        why: "Clock times take 'at': at 6, at noon, at midnight." },
      { type: "mc", q: "He's good ___ mathematics.", options: ["in", "at", "on", "for"], answer: "at",
        why: "'Good at' + skill/subject is a fixed combination." },
      { type: "mc", q: "I'm interested ___ photography.", options: ["in", "on", "at", "for"], answer: "in",
        why: "'Interested in' is a fixed combination." },
      { type: "mc", q: "The book is ___ the table.", options: ["in", "on", "at", "to"], answer: "on",
        why: "'On' for a surface contact." },
      { type: "mc", q: "We travelled ___ train.", options: ["by", "on", "in", "with"], answer: "by",
        why: "Means of transport take 'by': by train, by car, by plane." },
      { type: "mc", q: "Finish it ___ Friday at the latest.", options: ["in", "until", "by", "on"], answer: "by",
        why: "'By' = not later than a deadline. 'Until' = continuing up to a time." },
    ],
  },
  {
    id: "conditionals",
    title: "Conditionals",
    blurb: "if-clauses, zero → third",
    questions: [
      { type: "mc", q: "If you heat ice, it ___.", options: ["melts", "will melt", "would melt", "melted"], answer: "melts",
        why: "Zero conditional (general truth): if + present, present." },
      { type: "mc", q: "If it rains tomorrow, we ___ at home.", options: ["stay", "will stay", "would stay", "stayed"], answer: "will stay",
        why: "First conditional (real future): if + present, will + verb." },
      { type: "mc", q: "If I ___ rich, I would travel the world.", options: ["am", "was", "were", "will be"], answer: "were",
        why: "Second conditional (unreal present): if + past, would. 'Were' is standard for all persons." },
      { type: "mc", q: "If she had studied, she ___ the exam.", options: ["would pass", "passed", "would have passed", "will pass"], answer: "would have passed",
        why: "Third conditional (unreal past): if + past perfect, would have + participle." },
      { type: "fill", q: "Type the verb: 'If I had known, I ___ (come) earlier.'", answer: ["would have come"],
        why: "Third conditional result: would have + past participle." },
      { type: "mc", q: "I would help you if I ___ time.", options: ["have", "had", "will have", "would have"], answer: "had",
        why: "Second conditional if-clause uses the past simple." },
    ],
  },
  {
    id: "modals",
    title: "Modal Verbs",
    blurb: "can / must / should / might",
    questions: [
      { type: "mc", q: "You ___ smoke here. It's forbidden.", options: ["mustn't", "don't have to", "shouldn't", "can"], answer: "mustn't",
        why: "'Mustn't' = prohibition. 'Don't have to' = it's not necessary (very different!)." },
      { type: "mc", q: "It's late. You ___ be tired.", options: ["must", "can", "should", "might not"], answer: "must",
        why: "'Must' for a logical deduction you're sure about." },
      { type: "mc", q: "You ___ pay now; you can pay later.", options: ["mustn't", "don't have to", "can't", "shouldn't"], answer: "don't have to",
        why: "'Don't have to' = no obligation / not necessary." },
      { type: "mc", q: "___ you help me, please?", options: ["Must", "Could", "Should", "May"], answer: "Could",
        why: "'Could' is a polite way to make a request." },
      { type: "mc", q: "He ___ come, but I'm not sure.", options: ["must", "might", "should", "can"], answer: "might",
        why: "'Might' for possibility / uncertainty." },
      { type: "mc", q: "You ___ see a doctor about that cough.", options: ["should", "must not", "can't", "might"], answer: "should",
        why: "'Should' for advice / recommendation." },
    ],
  },
  {
    id: "comparatives",
    title: "Comparatives & Superlatives",
    blurb: "bigger, more / the most",
    questions: [
      { type: "fill", q: "Type the comparative: 'This box is ___ (heavy) than that one.'", answer: ["heavier"],
        why: "One/two-syllable adjective ending in -y → drop y, add -ier: heavier." },
      { type: "fill", q: "Type the form: 'It's the ___ (interesting) book I've read.'", answer: ["most interesting"],
        why: "Long adjectives form the superlative with 'most': the most interesting." },
      { type: "mc", q: "Today is ___ than yesterday.", options: ["hot", "hotter", "more hot", "hottest"], answer: "hotter",
        why: "Short adjective: double the consonant + -er → hotter." },
      { type: "mc", q: "This is ___ film I've ever seen.", options: ["the worse", "the worst", "worse", "baddest"], answer: "the worst",
        why: "Irregular: bad → worse → the worst." },
      { type: "fill", q: "Type the comparative: 'She speaks English ___ (good) than me.'", answer: ["better"],
        why: "Irregular: good/well → better → best." },
      { type: "mc", q: "My new phone is ___ expensive than the old one.", options: ["more", "most", "much", "the more"], answer: "more",
        why: "Long adjective comparative uses 'more': more expensive." },
    ],
  },
  {
    id: "reported",
    title: "Reported Speech",
    blurb: "He said that…",
    questions: [
      { type: "mc", q: "\"I am tired.\" → She said she ___ tired.", options: ["is", "was", "were", "has been"], answer: "was",
        why: "Reported speech shifts present → past: am → was." },
      { type: "mc", q: "\"I will call you.\" → He said he ___ call me.", options: ["will", "would", "is going to", "won't"], answer: "would",
        why: "will → would in reported speech." },
      { type: "mc", q: "\"Do you like it?\" → She asked ___ I liked it.", options: ["that", "if", "do", "what"], answer: "if",
        why: "Yes/no questions become reported with 'if' or 'whether'." },
      { type: "mc", q: "\"I saw him yesterday.\" → He said he ___ him the day before.", options: ["saw", "has seen", "had seen", "sees"], answer: "had seen",
        why: "Past simple → past perfect: saw → had seen." },
      { type: "mc", q: "\"Close the door.\" → She told me ___ the door.", options: ["close", "to close", "closing", "closed"], answer: "to close",
        why: "Commands become 'tell someone to + verb'." },
    ],
  },
];
